const ExLibrary = [

            // Strength ========
            {name: "Calf Raises", type:"exercise", targets:["Strength", "Calves"]},
            {name: "Clamshell", type:"exercise", targets:["Strength", "Groin"]},
            {name: "Glute Bridge", type:"exercise", targets:["Strength", "Glutes"]},
            {name: "High Plank", type:"exercise", targets:["Strength", "Core"]},
            {name: "Landing kicks", type:"exercise", targets:["Strength", "Glutes","Legs","Quads"]},
            {name: "Landing Position Hold", type:"exercise", targets:["Strength", "Legs", "Glutes"]},
            {name: "Lower Back Extensions", type:"exercise", targets:["Strength", "Back"]},
            {name: "Low plank", type:"exercise", targets:["Strength", "Core"]},
            {name: "Lunge", type:"exercise", targets:["Strength", "Legs", "Glutes"]},
            {name: "Lying Leg Raises", type:"exercise", targets:["Strength", "Core"]},
            {name: "Push-up", type:"exercise", targets:["Strength", "Chest", "Arms"]},
            {name: "Russian Twists", type:"exercise", targets:["Strength", "Core", "Power"]},
            {name: "Squat", type:"exercise", targets:["Strength", "Legs", "Quads"]},
            {name: "Superman", type:"exercise", targets:["Strength", "Back"]},
            {name: "V-ups", type:"exercise", targets:["Strength", "Core"]},
            {name: "Wall Sit", type:"exercise", targets:["Strength", "Legs", "Glutes"]},
            

            // Balance ========
            {name: "Arabesque Hold", type:"exercise", targets:["Strength", "Balance","Glutes", "Hamstrings"]},
            {name: "Bosu Ball Balance", type:"exercise", targets:["Balance"]},
            {name: "Camel hold", type:"exercise", targets:["Hamstrings"]},
            {name: "Closed-eye landing", type:"exercise",targets:["Balance"]},
            {name: "Heel-to-Toe Walk", type:"exercise", targets:["Balance"]},
            {name: "Pistol Squat", type:"exercise", targets:["Strength", "Balance","Legs", "Glutes"]},
            {name: "Single-leg Stand", type:"exercise", targets:["Balance"]},
            {name: "Stability Ball Exercises", type:"exercise", targets:["Balance"]},
            {name: "Yoga Tree Pose", type:"exercise", targets:["Balance"]},
            
            
            // Power ========
            {name: "Backward swizzle jump + tap or 1/2turn", type:"exercise", targets:["Power"]},
            {name: "Box Jump", type:"exercise", targets:["Legs", "Quads","Power"]},
            {name: "Broad Jump", type:"exercise", targets:["Legs", "Power"]},
            {name: "Correr zancadas + waltz swing + h", type:"exercise", targets:["Hip flexors","Power"]},
            {name: "Fwd skater jumps", type:"exercise", targets:["Calves","Power"]},
            {name: "Lateral Bounds", type:"exercise", targets:["Legs", "Power"]},
            {name: "Skater Hops", type:"exercise", targets:["Legs", "Power"]},
            {name: "Tap Jump", type:"exercise", targets:["Legs", "Calves"]},
            {name: "Tuck Jumps", type:"exercise", targets:["Legs", "Core","Power"]},
            {name: "3➡️salto + clavar (2p) + 🔁", type:"exercise", targets:["Power"]},
            {name: "➡️salto + ⬆️salto + clavar (1p)", type:"exercise", targets:["Power"]},
            {name: "3➡️salto + 3⬅️salto + clavar (1p)", type:"exercise", targets:["Power"]},
            {name: "3➡️salto + 3⬅️salto + landing (2p)", type:"exercise", targets:["Power"]},
            {name: "a", type:"exercise", targets:["Power"]},
            {name: "b", type:"exercise", targets:["Power"]},
            {name: "c", type:"exercise", targets:["Power"]},
            {name: "d", type:"exercise", targets:["Power"]},
            {name: "e", type:"exercise", targets:["Power"]},

            // Cardio ========
            {name: "Burpees", type:"exercise", targets:["Cardio"]},
            {name: "High Knees", type:"exercise", targets:["Cardio"]},
            {name: "Jumping Jacks", type:"exercise", targets:["Cardio"]},
            {name: "Mountain Climbers", type:"exercise", targets:["Cardio","Power"]},

            // Stretches ========
            {name: "90/90 stretch", type:"stretch", targets:["Hips"]},
            {name: "Ankle under couch", type:"stretch", targets:["Ankles"]},
            {name: "Ankle rolls", type:"stretch", targets:["Ankles"]},
            {name: "Arabesque", type:"stretch", targets:["Extensions"]},
            {name: "Attitude", type:"stretch", targets:["Extensions"]},
            {name: "Backbend", type:"stretch", targets:["Back"]},
            {name: "Bridge", type:"stretch", targets:["Back"]},
            {name: "Butterfly stretch", type:"stretch", targets:["Hips"]},
            {name: "Cat-cow", type:"stretch", targets:["Back"]},
            {name: "Child's pose", type:"stretch", targets:["Back"]},
            {name: "Clamshell", type:"stretch", targets:["Turnout"]},
            {name: "Cobra", type:"stretch", targets:["Back"]},
            {name: "Couch stretch", type:"stretch", targets:["Quads"]},
            {name: "Cross-body shoulder stretch", type:"stretch", targets:["Shoulders"]},
            {name: "Developpe", type:"stretch", targets:["Extensions"]},
            {name: "Dorsiflexion stretch", type:"stretch", targets:["Ankles"]},
            {name: "Extended lunge", type:"stretch", targets:["Hamstrings"]},
            {name: "Frog pose", type:"stretch", targets:["Hips"]},
            {name: "Front splits", type:"stretch", targets:["Front split"]},
            {name: "High kick", type:"stretch", targets:["Hamstrings"]},
            {name: "Lunge", type:"stretch", targets:["Hips"]},
            {name: "Lunge", type:"stretch", targets:["Front split"]},
            {name: "Lying spine twist", type:"stretch", targets:["Back"]},
            {name: "Lying quad stretch", type:"stretch", targets:["Quads"]},
            {name: "Pancake", type:"stretch", targets:["Middle split","Hips"]},
            {name: "Passe", type:"stretch", targets:["Extensions"]},
            {name: "Plantarflexion stretch", type:"stretch", targets:["Ankles"]},
            {name: "Pull arm behind head", type:"stretch", targets:["Shoulders"]},
            {name: "Seated turnout stretch", type:"stretch", targets:["Turnout"]},
            {name: "Sciatic glides", type:"stretch", targets:["Hamstrings"]},
            {name: "Standing hamstring stretch", type:"stretch", targets:["Hamstrings"]},
            {name: "Standing pancake", type:"stretch", targets:["Middle split","Hips"]},
            {name: "Standing turnout stretch", type:"stretch", targets:["Turnout"]},
            {name: "Straddle", type:"stretch", targets:["Middle split"]},
            {name: "Wall shoulder stretch", type:"stretch", targets:["Shoulders"]},
];